version: '3.8'

services:
  music_bot:
    build: .
    container_name: cafe-des-artistes
    restart: unless-stopped
    volumes:
      - ./src/config/config.yaml:/app/src/config/config.yaml:ro  
      - ./logs:/app/logs
    environment:
      - TZ=America/Montreal  # Set your timezone
    labels:
      - "traefik.enable=false"  # Keep as false if Traefik should ignore this service
    networks:
      - traefik-network  # Connect to the shared Traefik network

networks:
  traefik-network:
    external: true  # Indicates that this network is managed outside this Compose file
